package dev.mutagen.git;

import dev.mutagen.generator.GeneratedTest;
import dev.mutagen.mutation.MutationLoopResult;

import java.util.List;
import java.util.Locale;

/**
 * Builds the markdown body for the MR/PR that Mutagen opens.
 *
 * <p>Includes: test classes generated, endpoints covered, mutation score before/after.
 */
public class MrDescription {

    private MrDescription() {}

    public static String build(List<GeneratedTest> tests, MutationLoopResult loopResult, int threshold) {
        int totalEndpoints = tests.stream()
                .mapToInt(t -> t.getEndpoints().size())
                .sum();

        StringBuilder sb = new StringBuilder();
        sb.append("## 🤖 Mutagen: AI-Generated Integration Tests\n\n");
        sb.append("Generated by **Mutagen** — AI-powered integration test generator for Spring Boot.\n\n");

        sb.append("### What's included\n");
        sb.append("- **").append(tests.size()).append(" test class")
          .append(tests.size() == 1 ? "" : "es").append("** generated\n");
        sb.append("- **").append(totalEndpoints).append(" endpoint")
          .append(totalEndpoints == 1 ? "" : "s").append("** covered\n\n");

        sb.append("### Mutation coverage\n\n");
        sb.append("| | Score |\n|---|---|\n");
        sb.append("| Before gap-fill | ").append(formatScore(loopResult.initialScore())).append(" |\n");
        sb.append("| After gap-fill  | ").append(formatScore(loopResult.finalScore())).append(" |\n");
        sb.append("| Target          | ").append(threshold).append("% |\n\n");

        if (loopResult.iterationsRun() > 1) {
            sb.append("*Pitest ran ").append(loopResult.iterationsRun()).append(" iteration")
              .append(loopResult.iterationsRun() == 1 ? "" : "s").append(".*\n\n");
        }

        sb.append("### Generated test classes\n\n");
        for (GeneratedTest test : tests) {
            sb.append("- `").append(test.getTestClassName()).append("` — `")
              .append(test.getPackageName()).append("`");
            if (!test.getEndpoints().isEmpty()) {
                sb.append(" (").append(test.getEndpoints().size()).append(" endpoint")
                  .append(test.getEndpoints().size() == 1 ? "" : "s").append(")");
            }
            sb.append("\n");
        }

        sb.append("\n---\n");
        sb.append("*Generated by Mutagen · ");
        sb.append("Do not manually edit these files — re-run Mutagen to regenerate.*\n");

        return sb.toString();
    }

    private static String formatScore(double score) {
        if (score < 0) return "n/a";
        return String.format(Locale.US, "%.1f%%", score);
    }
}
